# Generated by Django 3.2.7 on 2021-12-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0003_admin_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_b', models.CharField(max_length=200)),
                ('f_date', models.DateTimeField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.bloodbank')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.donor')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.receiver')),
            ],
            options={
                'db_table': 'bloodbank_feedback',
            },
        ),
    ]
